spring:
  application:
    name: submify-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.dbwoifhjphzpemwqaunj
    password: SahilProject@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
cors:
  allowed-origins: http://localhost:5173