spring:
  application:
    name: submify-backend

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/submify

    username: postgres

    password: Sahil@123

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.PostgreSQLDialect